# This is a basic workflow to help you get started with Actions

name: Updating Master branch with GH-Pages Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ gh-pages ]


jobs:
  masterPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset master branch
        run: |
          git fetch origin gh-pages:gh-pages
          git reset --hard gh-pages
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          branch: masterPromotion
